# from: https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
language: generic

matrix:
 include:
  - os: linux
    sudo: required
    python: 2.7
  - os: linux
    sudo: required
    python: 3.5
  - os: linux
    sudo: required
    python: 3.6
  - os: osx
    language: generic
    python: 2.7
  - os: osx
    language: generic
    python: 3.5
  - os: osx
    language: generic
    python: 3.6

install:
 - sudo apt-get update
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7"]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
   else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
   fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a

 - conda create -q -n build-environment python=$TRAVIS_PYTHON_VERSION
 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
 - source activate build-environment
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - source activate test-environment
 - pip install pytest pytest-cov codecov

before_script:
 - source activate build-environment
 - python setup.py build_ext --inplace
 - python setup.py bdist_wheel
 - source activate test-environment
 - pip install --find-links=dist neuroglia

script:
 - source activate test-environment
 - pytest --cov=neuroglia
 - codecov
